version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build: ./backend
    container_name: task-manager-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      CLERK_PUBLISHABLE_KEY: pk_test_c3VpdGVkLXdlcmV3b2xmLTE3LmNsZXJrLmFjY291bnRzLmRldiQ
    ports:
      - "8080:8080"
    networks:
      - task-manager-network
    volumes:
      - ./uploads:/app/uploads

  # Frontend React
  frontend:
    build: ./frontend
    container_name: task-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - task-manager-network


networks:
  task-manager-network:
    driver: bridge
